### PR TITLE
Use background normalization in ellipse fitting

### PR DESCRIPTION
**Pull request by melix**
This commit introduces background normalization during ellipse fitting. This turns out to greatly help with difficult edge detection, in particular near UV (calcium).

### CODE REVIEW

**Comment by stefanoaz** [comment]
Thanks Cédric. I was having issues with edge detection in Ca-K - the workaround was to revert to CLAHE for contrast enhancement instead of the default Autostretch. Glad you found a more robust method.

**Comment by melix** [comment]
Did you have a chance to test the dev version with this change? Does it help ?

**Comment by stefanoaz** [comment]
I was about to start processing Ca-K, so I'll download the beta and let you know.

**Comment by stefanoaz** [comment]
Hi Cédric:

The dev 2.4.5 version definitely helps. However, seemingly just for the Ca-K case, CLAHE still produces better edges - the Autostretch seems to leave a ring artifact. I have a Bin2 ser file link you can download to test - here:  https://www.dropbox.com/scl/fi/hnaw00seiovdje2uz42v7/Sun_073240-copy.ser?rlkey=h3lf89yk97vgdnxyy27j6dsc3&dl=0 

Of a set of three, this file has the lowest camera gain. As the gain goes up and the artifact reduces. But CLAHE leaves no artifact even in this low gain case.

Steve

**Comment by melix** [comment]
Thanks I'll take a look tomorrow

**Comment by stefanoaz** [comment]
Cédric:

Just a comment -  For H-alpha I'm finding that your Autostretch does a much better job of reducing the banding artifacts versus CLAHE. Autostretch seems to be more tolerant when my x/y ratio goes below 1 (0.68 in this case where I'm trying to do fast scans at 20x to do image stacking). CLAHE is leaving bands where autostretch is free of them.

steve

**Comment by melix** [comment]
I can confirm that CLAHE gives much better results with your file. I think it's because the average level of signal is fairly low, which confuses my autohistogram algorithm.

Regarding banding correction, there should be no difference in banding correction between CLAHE and autostretch, because the correction is done before histogram transformation. However it is possible that CLAHE "enhances" details that it shouldn't, it's a common issue with CLAHE.

**Pull request merged**
